"use strict";

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("monstro", {
  // El renderer ajusta el topbar según la plataforma (hueco de los traffic lights solo en macOS).
  platform: process.platform,
  authStatus: () => ipcRenderer.invoke("auth:status"),
  getConfig: () => ipcRenderer.invoke("config:get"),
  setConfig: (partial) => ipcRenderer.invoke("config:set", partial),
  suggestRepos: () => ipcRenderer.invoke("repos:suggest"),
  localPickRoot: () => ipcRenderer.invoke("local:pickRoot"),
  localRepos: () => ipcRenderer.invoke("local:repos"),
  localRepoInfo: (dir) => ipcRenderer.invoke("local:repoInfo", { dir }),
  localProposeTask: (payload) => ipcRenderer.invoke("local:proposeTask", payload),
  localCreateTask: (payload) => ipcRenderer.invoke("local:createTask", payload),
  localProposeEpic: (payload) => ipcRenderer.invoke("local:proposeEpic", payload),
  localCreateEpicTask: (payload) => ipcRenderer.invoke("local:createEpicTask", payload),
  localSearchIssues: (query) => ipcRenderer.invoke("local:searchIssues", { query }),
  localMyTasks: () => ipcRenderer.invoke("local:myTasks"),
  localProposePlan: (payload) => ipcRenderer.invoke("local:proposePlan", payload),
  localLinkTask: (payload) => ipcRenderer.invoke("local:linkTask", payload),
  localItemStatuses: (items) => ipcRenderer.invoke("local:itemStatuses", { items }),
  localHistoryList: () => ipcRenderer.invoke("localHistory:list"),
  localHistoryRemove: (id) => ipcRenderer.invoke("localHistory:remove", { id }),
  localHistoryClear: () => ipcRenderer.invoke("localHistory:clear"),
  agentsStart: (payload) => ipcRenderer.invoke("agents:start", payload),
  agentsList: () => ipcRenderer.invoke("agents:list"),
  agentsGet: (runId) => ipcRenderer.invoke("agents:get", { runId }),
  agentsResume: (runId, projectDir, guidance) => ipcRenderer.invoke("agents:resume", { runId, projectDir, guidance }),
  agentsStop: (runId, projectDir) => ipcRenderer.invoke("agents:stop", { runId, projectDir }),
  agentsRemove: (runId) => ipcRenderer.invoke("agents:remove", { runId }),
  agentsOpenEditor: (projectDir, worktree) => ipcRenderer.invoke("agents:openEditor", { projectDir, worktree }),
  agentsFinalize: (runId, projectDir, commitMessage) => ipcRenderer.invoke("agents:finalize", { runId, projectDir, commitMessage }),
  agentsDiff: (projectDir, worktree, base, branch) => ipcRenderer.invoke("agents:diff", { projectDir, worktree, base, branch }),
  agentsMrStatuses: (runId) => ipcRenderer.invoke("agents:mrStatuses", { runId }),
  agentsCleanupWorktree: (runId, projectDir) => ipcRenderer.invoke("agents:cleanupWorktree", { runId, projectDir }),
  // Eventos push de los agentes (timeline/estado/notificación). Devuelve un de-suscriptor.
  onAgentEvent: (channel, cb) => {
    const ok = ["agents:event", "agents:run", "agents:notify"];
    if (!ok.includes(channel)) return () => {};
    const listener = (_e, payload) => cb(payload);
    ipcRenderer.on(channel, listener);
    return () => ipcRenderer.removeListener(channel, listener);
  },
  listPRs: (repo, states) => ipcRenderer.invoke("prs:list", { repo, states }),
  searchPRs: (repos, states) => ipcRenderer.invoke("prs:search", { repos, states }),
  prDetail: (repo, number) => ipcRenderer.invoke("pr:detail", { repo, number }),
  mergePR: (args) => ipcRenderer.invoke("pr:merge", args),
  updateBranch: (nodeId) => ipcRenderer.invoke("pr:updateBranch", { nodeId }),
  prFiles: (repo, number) => ipcRenderer.invoke("pr:files", { repo, number }),
  prConversation: (repo, number) => ipcRenderer.invoke("pr:conversation", { repo, number }),
  commentIssue: (repo, number, body) => ipcRenderer.invoke("pr:commentIssue", { repo, number, body }),
  commentInline: (repo, number, comment) => ipcRenderer.invoke("pr:commentInline", { repo, number, comment }),
  replyThread: (repo, number, commentDatabaseId, body) =>
    ipcRenderer.invoke("pr:replyThread", { repo, number, commentDatabaseId, body }),
  resolveThread: (threadId, resolved) => ipcRenderer.invoke("pr:resolveThread", { threadId, resolved }),
  submitReview: (repo, number, review) => ipcRenderer.invoke("pr:submitReview", { repo, number, review }),
  dismissReview: (repo, number, reviewId, message) =>
    ipcRenderer.invoke("pr:dismissReview", { repo, number, reviewId, message }),
  aiReview: (title, body, files) => ipcRenderer.invoke("ai:review", { title, body, files }),
  aiStatus: () => ipcRenderer.invoke("ai:status"),
  aiPing: () => ipcRenderer.invoke("ai:ping"),
  draftsList: (key) => ipcRenderer.invoke("drafts:list", { key }),
  draftsSave: (key, items) => ipcRenderer.invoke("drafts:save", { key, items }),
  draftsKeys: () => ipcRenderer.invoke("drafts:keys"),
  defaultBranch: (repo) => ipcRenderer.invoke("history:branches", { repo }),
  historyGraph: (repo, branchSpecs) => ipcRenderer.invoke("history:graph", { repo, branchSpecs }),
  createBranch: (repo, branch, sha) => ipcRenderer.invoke("git:createBranch", { repo, branch, sha }),
  forceUpdateBranch: (repo, branch, sha) => ipcRenderer.invoke("git:forceUpdate", { repo, branch, sha }),
  cherryPick: (repo, sha, branch, dryRun) => ipcRenderer.invoke("pr:cherryPick", { repo, sha, branch, dryRun }),
  revertPR: (repo, number) => ipcRenderer.invoke("pr:revert", { repo, number }),
  setPrDraft: (nodeId, toDraft) => ipcRenderer.invoke("pr:setDraft", { nodeId, toDraft }),
  listMilestones: () => ipcRenderer.invoke("milestones:list"),
  milestoneIssues: (title, includeClosed) => ipcRenderer.invoke("milestones:issues", { title, includeClosed }),
  groupLabels: () => ipcRenderer.invoke("issues:groupLabels"),
  groupProjects: () => ipcRenderer.invoke("issues:groupProjects"),
  updateIssue: (projectId, iid, patch) => ipcRenderer.invoke("issues:update", { projectId, iid, patch }),
  summarizeMilestone: (milestoneTitle, issues) => ipcRenderer.invoke("milestones:summary", { milestoneTitle, issues }),
  publishMilestoneSnippet: (title, contentMarkdown) => ipcRenderer.invoke("milestones:publishSnippet", { title, contentMarkdown }),
  releasesDefaults: () => ipcRenderer.invoke("releases:defaults"),
  generateReleaseBranches: (payload) => ipcRenderer.invoke("releases:generate", payload),
  createReleases: (payload) => ipcRenderer.invoke("releases:create", payload),
  releaseStatus: (projectId, ref) => ipcRenderer.invoke("releases:status", { projectId, ref }),
  openExternal: (url) => ipcRenderer.invoke("shell:open", url),
  notify: (title, body) => ipcRenderer.invoke("notify", { title, body }),
  dockBadge: (text) => ipcRenderer.invoke("dock:badge", text),
  selftestRenderComplete: () => ipcRenderer.send("selftest:render-complete"),
});
